<?php

namespace testBundle\Repository;

/**
 * DonataireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonataireRepository extends \Doctrine\ORM\EntityRepository
{
}
